config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :form_data_sets

  map.resources :form_datas

  map.resources :form_group_assignments

  map.resources :forms

  map.resources :group_element_assignments
  map.resources :form_groups
  map.resources :form_elements

  map.form_report '/forms/report/:id', :controller => 'form_data_sets', :action => 'report'

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/form_group.rb
class FormGroup < ActiveRecord::Base

  has_many :group_element_assignments
  has_many :form_elements, :through => :group_element_assignments

  has_many :form_group_assignments
  has_many :forms, :through => :form_group_assignments

  validates_presence_of :label

end

app/controllers/form_groups_controller.rb
class FormGroupsController < ApplicationController

  def index
    @form_group = FormGroup.new
    @form_groups = FormGroup.all
    @form_elements = FormElement.all
  end

  def create
    @form_group = FormGroup.new(params[:form_group])
    if @form_group.save
      notify_success :added, :form_group
      redirect_to form_groups_url
    else
      notify_failure :add, :form_group
      @form_groups = FormGroup.all
      render :action => :index
    end
  end

  def destroy
    form_group = FormGroup.find(params[:id].to_i)
    if form_group.destroy
      notify_success :removed, :group
    else
      notify_failure :remove, :group
    end

    redirect_to form_groups_url
  end

  def edit
    @form_group = FormGroup.find(params[:id].to_i)
  end

  def update
    @form_group = FormGroup.find(params[:id].to_i)
    if @form_group.update_attributes(params[:form_group])
      notify_success :updated, :form_group
      redirect_to form_groups_url
    else
      notify_failure :update, :form_group
      render :edit
    end
  end

end

app/helpers/form_groups_helper.rb
module FormGroupsHelper
end

app/views/form_groups/edit.html.erb
<% form_for @form_group do |f| %>
  <%= f.label :label %><br/>
  <%= f.text_field :label %><br/>
  <%= f.label :description %><br/>
  <%= f.text_area :description, :rows => 10, :cols => 30 %><br/>
  <%= f.submit 'Update' %>
<% end %>

app/views/form_groups/index.html.erb
<ul class='form_groups' style="margin: 0; list-style-type:none;">
  <% @form_groups.each do |form_group| %>
    <li class='form_group_item' id='form_group_<%= form_group.id %>'>
      <b><%= form_group.label %></b>
      <%= link_to 'delete', form_group_url(form_group.id),
                  :method => :delete,
                  :confirm => 'Do you want to remove this group?' %> |
      <%= link_to 'edit', edit_form_group_url(form_group.id) %>

      <ul class='form_group_elements' style="margin: 0; list-style-type: none;">
        <% form_group.group_element_assignments.each do |assignment| %>
          <li style="padding: 10px;">
            <%= assignment.form_element.label if assignment.form_element %> |
            <%= link_to 'delete', group_element_assignment_url(assignment.id),
                        :method => :delete,
                        :confirm => 'Do you really want to remove this assignment?' %>
          </li>
        <% end %>

        <li>
          <div class='form_group_element_assignment'>
            <%= error_messages_for :group_element_assignment %>
            <% form_for GroupElementAssignment.new do |f| %>
              <div class='form_elements_list'>
                <% @form_elements.each do |fe| %>
                  <input type='checkbox' id='form_element_<%= fe.id %>'
                         value="<%= fe.id %>" name='form_element_ids[]'/>
                  <label for='form_element_<%= fe.id %>'><%= fe.label %></label><br/>
                <% end %>
              </div>
              <%= f.hidden_field :form_group_id, :value => form_group.id %>
              <%= f.submit 'assign' %>
            <% end %>
          </div>
        </li>
      </ul>


    </li>
  <% end %>
</ul>

<div class='form_group'>
  <h4>Add new form group</h4>
  <% form_for @form_group do |f| %>
    <%= f.label :label %><br/>
    <%= f.text_field :label %><br/>
    <%= f.label :description %><br/>
    <%= f.text_area :description, :rows => 10, :cols => 30 %><br/>
    <%= f.submit 'Save' %>
  <% end %>
</div>